p90soldier:
  health: 100
  width: 2
  height: 6
  speed: 1
  grenade_type: 1

scoutsoldier:
  health: 100
  width: 2
  height: 6
  speed: 1
  grenade_type: 2

idfsoldier:
  health: 100
  width: 2
  height: 6
  speed: 1
  grenade_type: 2

p90weapon:
  damage: 1
  ammo: 300
  scope: 30
  damage_reduction_coef: 0.8

scoutweapon:
  damage: 1
  ammo: 200
  scope: 30
  damage_reduction_coef: 0.8

idfweapon:
  damage: 1
  ammo: 500
  scope: 30
  damage_reduction_coef: 0.8

zombie:
  health: 100
  width: 2
  height: 6
  speed: 1
