p90soldier:
  health: 100
  width: 2
  height: 6
  speed: 1
  grenade_type: 1

scoutsoldier:
  health: 100
  width: 2
  height: 6
  speed: 1
  grenade_type: 2

idfsoldier:
  health: 100
  width: 2
  height: 6
  speed: 1
  grenade_type: 2

p90weapon:
  damage: 50
  ammo: 30
  scope: 2
  damage_reduction_coef: 0.8

scoutweapon:
  damage: 60
  ammo: 20
  scope: 2
  damage_reduction_coef: 0.8

idfweapon:
  damage: 80
  ammo: 50
  scope: 2
  damage_reduction_coef: 0.8

zombie:
  health: 100
  width: 2
  height: 6
  speed: 1