p90soldier:
  health: 100
  width: 2
  height: 6
  speed: 200
  grenade_type: 1

scoutsoldier:
  health: 100
  width: 2
  height: 6
  speed: 200
  grenade_type: 2

idfsoldier:
  health: 100
  width: 2
  height: 6
  speed: 200
  grenade_type: 2

p90weapon:
  damage: 1
  ammo: 300
  scope: 30
  damage_reduction_coef: 0.8

scoutweapon:
  damage: 1
  ammo: 200
  scope: 30
  damage_reduction_coef: 0.8

idfweapon:
  damage: 1
  ammo: 500
  scope: 30
  damage_reduction_coef: 0.8

zombie:
  health: 100
  width: 2
  height: 6
  speed: 150

grenade:
  speed: 600
  scope: 100
  duration: 1.5
  damage: 1000

poison:
  speed: 200
  scope: 6
  duration: 1.7
  damage: 0.2

smoke:
  speed: 600
  scope: 100
  duration: 1.5
  damage: 0.0

aerial:
  speed: 600
  scope: 100
  duration: 1.5
  damage: 0.0

clear_easy:
  infected: 1
  spear: 1
  witch: 1
  jumper: 1
  venom: 3

clear_normal:
  infected: 2
  spear: 2
  witch: 1
  jumper: 2
  venom: 1

clear_hard:
  infected: 4
  spear: 1
  witch: 2
  jumper: 3
  venom: 1

clear_insane:
  infected: 4
  spear: 4
  witch: 4
  jumper: 4
  venom: 4

survival_easy:
  infected: 1
  spear: 1
  witch: 1
  jumper: 1
  venom: 1

survival_normal:
  infected: 2
  spear: 2
  witch: 1
  jumper: 2
  venom: 1

survival_hard:
  infected: 4
  spear: 1
  witch: 2
  jumper: 3
  venom: 1

survival_insane:
  infected: 4
  spear: 4
  witch: 4
  jumper: 4
  venom: 4

