grenade:
  speed: 200
  scope: 100
  duration: 1.5
  damage: 1000

poison:
  speed: 200
  scope: 6
  duration: 1.7
  damage: 0.2

smoke:
  speed: 10
  scope: 100
  duration: 1.5
  damage: 0.0

aerial:
  speed: 600
  scope: 100
  duration: 1.5
  damage: 0.0