infected:
  health: 100
  width: 2
  height: 6
  speed: 150
  sight: 200
  listening_range: 400
  hit_scope: 20
  damage: 0.09
  die_cooldown: 10
  stunned_cooldown: 5

spear:
  health: 100
  width: 2
  height: 6
  speed: 150
  sight: 200
  listening_range: 400
  hit_scope: 20
  damage: 0.09
  die_cooldown: 10
  stunned_cooldown: 5

witch:
  health: 100
  width: 2
  height: 6
  speed: 150
  sight: 200
  listening_range: 400
  hit_scope: 20
  damage: 0.09
  die_cooldown: 10
  stunned_cooldown: 5
  scream_cooldown: 15
  scream_duration: 4

venom:
  health: 100
  width: 2
  height: 6
  speed: 150
  sight: 200
  listening_range: 400
  hit_scope: 20
  damage: 0.09
  die_cooldown: 10
  stunned_cooldown: 5
  throw_cooldown: 4.0
  throw_duration: 0.5

jumper:
  health: 100
  width: 2
  height: 6
  speed: 150
  sight: 200
  listening_range: 400
  hit_scope: 20
  damage: 0.09
  die_cooldown: 10
  stunned_cooldown: 5