@startuml
'https://plantuml.com/class-diagram

class Zombie {
    id
    move()
    attack()
    simulate()
}

class Venom {
    throw()
}

class Witch {
    scream()
}

Venom -|> Zombie
Witch -|> Zombie
Jumper -|> Zombie
Infected -|> Zombie
Spear -|> Zombie


@enduml